# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'music-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for music-app
  pod 'Moya'
  pod 'Moya-ObjectMapper'
  pod 'SDWebImage'
  pod 'SPAlert'
  pod 'RealmSwift'
  pod 'TactileSlider'
  pod 'JDStatusBarNotification'

end
